# textlintでの文法チェックのワークフロー
name: Lint

# Reviewdogでの指摘を有効に使うため、pull requestでのみ有効
on:
  pull_request:
    # Pull Requestかつ
    # 以下のファイルに変更があった場合、このWorkflowを実行
    paths:
      - "prh.yml"
      - ".textlintrc"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/lint.yaml"
      - "**.tex"

jobs:
  lint:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    env:
      # reviewdogのバージョンを固定
      REVIEWDOG_VER: 0.11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "14.x"

      - name: Restore cache if available
        uses: actions/cache@v3.0.7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Restore reviewdog if available
        id: reviewdogcache
        uses: actions/cache@v3.0.7
        with:
          path: ~/bin
          key: ${{ runner.os }}-${{ env.REVIEWDOG_VER }}
          restore-keys: |
            ${{ runner.os }}-${{ env.REVIEWDOG_VER }}

      - name: Setup reviewdog
        if: steps.reviewdogcache.outputs.cache-hit != 'true'
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin v$REVIEWDOG_VER

      # 依存関係の構築とtextlintの実行
      - name: Run lint
        run: |
          npm ci
          npm run lint

      # ↑のステップでtextlintが違反を検知した場合のみ実行
      - name: Run reviewdog
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run lint-style | $HOME/bin/reviewdog -f=checkstyle -name="textlint" -diff="Git diff HEAD^" -reporter=github-pr-review
